### ISSUE TITLE
Exception in Github onLogin callback

### ISSUE THREAD

**Issue by jykae** [apinf/api-umbrella-dashboard#1126]
There is some legacy code to be removed onLogin callback, that throws exception every time user uses Github login, https://github.com/apinf/api-umbrella-dashboard/blob/develop/server/accounts.js#L60

```
I20160613-10:46:10.675(3)? Exception in onLogin callback: ReferenceError: GitHub is not defined
I20160613-10:46:10.675(3)?     at server/accounts.js:67:20
I20160613-10:46:10.675(3)?     at runAndHandleExceptions (packages/callback-hook/hook.js:133:1)
I20160613-10:46:10.675(3)?     at packages/callback-hook/hook.js:140:1
I20160613-10:46:10.675(3)?     at packages/accounts-base/accounts_server.js:167:5
I20160613-10:46:10.675(3)?     at [object Object]._.extend.each (packages/callback-hook/hook.js:109:1)
I20160613-10:46:10.676(3)?     at AccountsServer.Ap._successfulLogin (packages/accounts-base/accounts_server.js:166:21)
I20160613-10:46:10.676(3)?     at AccountsServer.Ap._attemptLogin (packages/accounts-base/accounts_server.js:349:10)
I20160613-10:46:10.676(3)?     at [object Object].methods.login (packages/accounts-base/accounts_server.js:526:21)
I20160613-10:46:10.676(3)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
I20160613-10:46:10.676(3)?     at packages/ddp-server/livedata_server.js:711:19
```

**Comment by jykae** [comment]
@bajiat I am interested to cleaning up this.
