### ISSUE TITLE
Server error (500) when uploading swagger documentation

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#1152]
On a fresh clone of the `develop` branch, the documentation file upload produces the following error:

# Server console
```
Exception while invoking method '/apiBackends/update' ReferenceError: fields is not defined
     at update (apis/collection/permissions.js:48:20)
     at packages/allow-deny/allow-deny.js:308:12
     at packages/underscore/underscore.js:235:1
     at _.each._.forEach (packages/underscore/underscore.js:108:1)
     at Function._.some._.any (packages/underscore/underscore.js:234:1)
     at [object Object].CollectionPrototype._validatedUpdate (packages/allow-deny/allow-deny.js:306:9)
     at [object Object].m.(anonymous function) (packages/allow-deny/allow-deny.js:156:46)
     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
     at packages/ddp-server/livedata_server.js:711:19
     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
```
# Firefox browser console error
```
Object { 
  stack: "Meteor.makeErrorType/errorClass@htt…",
  error: 500, reason: "Internal server error",
  details: undefined,
  message: "Internal server error [500]",
  errorType: "Meteor.Error"
}
```

# Steps to reproduce
1. clone the Apinf repository
2. run `npm install`
3. run `meteor`
4. configure the API Umbrella/Elastic settings
5. register a user account
6. go to any API Backend
7. click the **Documentation** tab
8. click the **Manage** button
9. upload a Swagger JSON file
10. check the browser and server console for errors

# Environment
Chromium version 50.0.2661.102
Firefox 47
Ubuntu 16.04 (64-bit)

**Comment by brylie** [comment]
This could be an issue with our allow/deny rule(s) related to uploading files:

```
apis/collection/permissions.js:48:20
```
