### ISSUE TITLE
Error invoking Method 'adminAddUserToRole': Internal server error [500]

### ISSUE THREAD

**Issue by elnzv** [apinf/api-umbrella-dashboard#256]
Trying to add Admin role to user here: 
http://localhost:3000/admin/Users/[userId]/edit

Have this error in client console:
```console
events.coffee:20 adding user
debug.js:41 Error invoking Method 'adminAddUserToRole': Internal server error [500]
```

And this in server console:

```console
I20150721-12:45:31.096(3)? Exception while invoking method 'adminAddUserToRole' Error: When the modifier option is true, validation object must have at least one operator
I20150721-12:45:31.096(3)?     at checkModifier (packages/aldeed:simple-schema/simple-schema-validation.js:271:1)
I20150721-12:45:31.096(3)?     at doValidation1 (packages/aldeed:simple-schema/simple-schema-validation.js:321:1)
I20150721-12:45:31.096(3)?     at doValidation (packages/aldeed:simple-schema/simple-schema-context.js:9:1)
I20150721-12:45:31.096(3)?     at SimpleSchemaValidationContext.simpleSchemaValidationContextValidate [as validate] (packages/aldeed:simple-schema/simple-schema-context.js:44:1)
I20150721-12:45:31.096(3)?     at [object Object].doValidate (packages/aldeed:collection2/collection2.js:317:1)
I20150721-12:45:31.096(3)?     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2/collection2.js:154:1)
I20150721-12:45:31.097(3)?     at Object._.extend._updateUserRoles (packages/alanning:roles/roles_common.js:680:1)
I20150721-12:45:31.097(3)?     at Object._.extend.addUsersToRoles (packages/alanning:roles/roles_common.js:145:1)
I20150721-12:45:31.097(3)?     at [object Object].Meteor.methods.adminAddUserToRole (packages/yogiben:admin/lib/server/methods.coffee:97:10)
I20150721-12:45:31.097(3)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)

```

**Comment by elnzv** [comment]
Since yogiben:admin is removed, it's no longer relevant.
