### ISSUE TITLE
Update links to social services on a home page.

### ISSUE THREAD

**Issue by frenchbread** [apinf/api-umbrella-dashboard#445]
Update links to social services (APInf Facebook, APInf Twitter), since domain name changed to apinf.io.
New links:
Facebook - https://www.facebook.com/APInf.io.
Twitter - https://twitter.com/APInf_io

**Comment by frenchbread** [comment]
@apinf/developers I would do it myself, but I am getting this error when running project locally:
```
W20150908-01:37:06.936(9)? (STDERR) /Users/damir/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:278
W20150908-01:37:06.937(9)? (STDERR) 						throw(ex);
W20150908-01:37:06.937(9)? (STDERR) 						      ^
W20150908-01:37:07.028(9)? (STDERR) Error: connect ECONNREFUSED
W20150908-01:37:07.028(9)? (STDERR)     at Object.Future.wait (/Users/damir/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
W20150908-01:37:07.028(9)? (STDERR)     at Object.call (packages/meteor/helpers.js:119:1)
W20150908-01:37:07.028(9)? (STDERR)     at Object.HTTP.get (packages/http/httpcall_common.js:45:1)
W20150908-01:37:07.028(9)? (STDERR)     at Object.apiUsers.getUsers (packages/brylie:api-umbrella/server/admin-api/v1/apiUsers.js:51:1)
W20150908-01:37:07.032(9)? (STDERR)     at [object Object].Meteor.methods.syncApiUmbrellaUsers (app/server/methods/apiUmbrellaWeb.js:5:58)
W20150908-01:37:07.032(9)? (STDERR)     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
W20150908-01:37:07.032(9)? (STDERR)     at packages/ddp/livedata_server.js:1530:1
W20150908-01:37:07.032(9)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
W20150908-01:37:07.034(9)? (STDERR)     at [object Object]._.extend.apply (packages/ddp/livedata_server.js:1529:1)
W20150908-01:37:07.035(9)? (STDERR)     at [object Object]._.extend.call (packages/ddp/livedata_server.js:1472:1)
W20150908-01:37:07.036(9)? (STDERR)     at app/server/startup.js:15:10
W20150908-01:37:07.036(9)? (STDERR)     at /Users/damir/Dev/meteorApps/api-umbrella-dashboard/.meteor/local/build/programs/server/boot.js:229:5
W20150908-01:37:07.036(9)? (STDERR)     - - - - -
W20150908-01:37:07.036(9)? (STDERR)     at errnoException (net.js:905:11)
W20150908-01:37:07.041(9)? (STDERR)     at Object.afterConnect [as oncomplete] (net.js:896:19)
```
Have someone got something similar or have an idea how to fix it?

**Comment by brylie** [comment]
Check what version of [brylie:meteor-api-umbrella]() you have in .packages. Also, make sure your settings file has the proper credentials and URL for *umbrella.apinf.io*, as we are deprecating *apinf.com*.

**Comment by frenchbread** [comment]
@brylie Thanks. Error is fixed now. The issue was in having old api key and api token. Got new ones, so now it is okay. 

PR #448 created. Please review
